/** Emoji data ported from SoulSync webui/static/chat.js (_EMOJI_DATA / ANIMATED_EMOJI). */

export interface EmojiCat { slug: string; icon: string; title: string; names: string[]; }

export const EMOJI: Record<string, string> = {
  "smile": "😄",
  "grin": "😁",
  "joy": "😂",
  "rofl": "🤣",
  "wink": "😉",
  "blush": "😊",
  "innocent": "😇",
  "heart_eyes": "😍",
  "star_struck": "🤩",
  "kissing_heart": "😘",
  "kissing": "😗",
  "yum": "😋",
  "stuck_out_tongue": "😛",
  "stuck_out_tongue_wink": "😜",
  "zany": "🤪",
  "raised_eyebrow": "🤨",
  "monocle": "🧐",
  "nerd": "🤓",
  "sunglasses": "😎",
  "disguised": "🥸",
  "partying": "🥳",
  "smirk": "😏",
  "unamused": "😒",
  "disappointed": "😞",
  "worried": "😟",
  "angry": "😠",
  "rage": "🤬",
  "cry": "😢",
  "sob": "😭",
  "scream": "😱",
  "flushed": "😳",
  "pleading": "🥺",
  "melting": "🫠",
  "cold_face": "🥶",
  "hot_face": "🥵",
  "nauseated": "🤢",
  "mind_blown": "🤯",
  "sleeping": "😴",
  "drool": "🤤",
  "thinking": "🤔",
  "shush": "🤫",
  "zipper_mouth": "🤐",
  "peeking": "🫣",
  "salute": "🫡",
  "dotted_face": "🫥",
  "skull": "💀",
  "clown": "🤡",
  "ghost": "👻",
  "alien": "👽",
  "robot": "🤖",
  "poop": "💩",
  "money": "🤑",
  "cowboy": "🤠",
  "rolling_eyes": "🙄",
  "grimace": "😬",
  "relieved": "😌",
  "shrug": "🤷",
  "facepalm": "🤦",
  "hugs": "🤗",
  "pensive": "😔",
  "confused": "😕",
  "upside_down": "🙃",
  "moai": "🗿",
  "thumbsup": "👍",
  "thumbsdown": "👎",
  "clap": "👏",
  "wave": "👋",
  "wave_hand": "👋",
  "pray": "🙏",
  "handshake": "🤝",
  "point_up": "☝️",
  "point_right": "👉",
  "point_left": "👈",
  "point_down": "👇",
  "ok_hand": "👌",
  "pinch": "🤌",
  "v": "✌️",
  "love_you": "🤟",
  "metal": "🤘",
  "call_me": "🤙",
  "crossed": "🤞",
  "muscle": "💪",
  "brain": "🧠",
  "eyes": "👀",
  "eye": "👁️",
  "tongue": "👅",
  "lips": "👄",
  "palms_up": "🫴",
  "heart_hands": "🫶",
  "middle_finger": "🖕",
  "raised_fist": "✊",
  "fist": "👊",
  "palm": "🤚",
  "pinching": "🤏",
  "writing": "✍️",
  "nail_polish": "💅",
  "heart": "❤️",
  "orange_heart": "🧡",
  "yellow_heart": "💛",
  "green_heart": "💚",
  "blue_heart": "💙",
  "purple_heart": "💜",
  "black_heart": "🖤",
  "white_heart": "🤍",
  "brown_heart": "🤎",
  "pink_heart": "🩷",
  "broken_heart": "💔",
  "heart_fire": "❤️‍🔥",
  "heart_exclamation": "❣️",
  "two_hearts": "💕",
  "revolving_hearts": "💞",
  "heartbeat": "💓",
  "heartpulse": "💗",
  "sparkling_heart": "💖",
  "cupid": "💘",
  "gift_heart": "💝",
  "heart_decoration": "💟",
  "kiss_mark": "💋",
  "hundred": "💯",
  "anger": "💢",
  "boom": "💥",
  "dizzy": "💫",
  "sweat_drops": "💦",
  "fire": "🔥",
  "sparkles": "✨",
  "star": "⭐",
  "glowing_star": "🌟",
  "shooting_star": "🌠",
  "notes": "🎵",
  "musical_note": "🎶",
  "headphones": "🎧",
  "guitar": "🎸",
  "cd": "💿",
  "vinyl": "📀",
  "mic": "🎤",
  "speaker": "🔊",
  "mute": "🔇",
  "studio_mic": "🎙️",
  "radio": "📻",
  "saxophone": "🎷",
  "accordion": "🪗",
  "drum": "🥁",
  "piano": "🎹",
  "trumpet": "🎺",
  "violin": "🎻",
  "banjo": "🪕",
  "maracas": "🪇",
  "long_drum": "🪘",
  "movie": "🎬",
  "tv": "📺",
  "camera": "📷",
  "video_camera": "📹",
  "clapper": "🎬",
  "film": "🎞️",
  "projector": "📽️",
  "popcorn": "🍿",
  "ticket": "🎫",
  "loudly_crying": "📢",
  "bell": "🔔",
  "mega": "📣",
  "dog": "🐶",
  "cat": "🐱",
  "fox": "🦊",
  "wolf": "🐺",
  "bear": "🐻",
  "panda": "🐼",
  "koala": "🐨",
  "tiger": "🐯",
  "lion": "🦁",
  "unicorn": "🦄",
  "horse": "🐴",
  "cow": "🐮",
  "pig": "🐷",
  "frog": "🐸",
  "monkey": "🐵",
  "chicken": "🐔",
  "penguin": "🐧",
  "bird": "🐦",
  "eagle": "🦅",
  "bat": "🦇",
  "owl": "🦉",
  "butterfly": "🦋",
  "bee": "🐝",
  "ladybug": "🐞",
  "snake": "🐍",
  "octopus": "🐙",
  "whale": "🐋",
  "dolphin": "🐬",
  "fish": "🐟",
  "shark": "🦈",
  "turtle": "🐢",
  "dragon": "🐉",
  "cactus": "🌵",
  "tree": "🌲",
  "palm_tree": "🌴",
  "seedling": "🌱",
  "herb": "🌿",
  "four_leaf": "🍀",
  "mushroom": "🍄",
  "rose": "🌹",
  "cherry_blossom": "🌸",
  "sunflower": "🌻",
  "rainbow": "🌈",
  "snowflake": "❄️",
  "tornado": "🌪️",
  "ocean": "🌊",
  "crescent_moon": "🌙",
  "sun": "☀️",
  "pizza": "🍕",
  "hamburger": "🍔",
  "fries": "🍟",
  "hotdog": "🌭",
  "taco": "🌮",
  "burrito": "🌯",
  "sushi": "🍣",
  "ramen": "🍜",
  "spaghetti": "🍝",
  "rice": "🍚",
  "curry": "🍛",
  "bento": "🍱",
  "egg": "🥚",
  "pancakes": "🥞",
  "waffle": "🧇",
  "bacon": "🥓",
  "steak": "🥩",
  "croissant": "🥐",
  "bread": "🍞",
  "bagel": "🥯",
  "pretzel": "🥨",
  "apple": "🍎",
  "grapes": "🍇",
  "watermelon": "🍉",
  "strawberry": "🍓",
  "peach": "🍑",
  "mango": "🥭",
  "banana": "🍌",
  "avocado": "🥑",
  "ice_cream": "🍦",
  "donut": "🍩",
  "cookie": "🍪",
  "cake": "🎂",
  "chocolate": "🍫",
  "candy": "🍬",
  "lollipop": "🍭",
  "beers": "🍻",
  "wine": "🍷",
  "cocktail": "🍸",
  "champagne": "🍾",
  "coffee": "☕",
  "tea": "🍵",
  "bubble_tea": "🧋",
  "juice": "🧃",
  "milk": "🥛",
  "beer": "🍺",
  "tropical_drink": "🍹",
  "mate": "🧉",
  "trophy": "🏆",
  "medal": "🏅",
  "gold_medal": "🥇",
  "silver_medal": "🥈",
  "bronze_medal": "🥉",
  "soccer": "⚽",
  "basketball": "🏀",
  "football": "🏈",
  "baseball": "⚾",
  "tennis": "🎾",
  "volleyball": "🏐",
  "rugby": "🏉",
  "cricket": "🏏",
  "golf": "⛳",
  "ping_pong": "🏓",
  "badminton": "🏸",
  "boxing": "🥊",
  "skateboard": "🛹",
  "surfing": "🏄",
  "swimming": "🏊",
  "biking": "🚴",
  "running": "🏃",
  "yoga": "🧘",
  "climbing": "🧗",
  "video_game": "🎮",
  "joystick": "🕹️",
  "dice": "🎲",
  "puzzle": "🧩",
  "chess": "♟️",
  "dart": "🎯",
  "bowling": "🎳",
  "billiards": "🎱",
  "slot_machine": "🎰",
  "fishing": "🎣",
  "kite": "🪁",
  "bulb": "💡",
  "flashlight": "🔦",
  "candle": "🕯️",
  "gem": "💎",
  "crown": "👑",
  "ring": "💍",
  "money_bag": "💰",
  "dollar": "💵",
  "credit_card": "💳",
  "chart": "📈",
  "chart_down": "📉",
  "calendar": "📅",
  "clipboard": "📋",
  "pushpin": "📌",
  "paperclip": "📎",
  "scissors": "✂️",
  "lock": "🔒",
  "unlock": "🔓",
  "key": "🔑",
  "hammer": "🔨",
  "wrench": "🔧",
  "gear": "⚙️",
  "magnet": "🧲",
  "link": "🔗",
  "battery": "🔋",
  "plug": "🔌",
  "computer": "💻",
  "phone": "📱",
  "hourglass": "⏳",
  "alarm": "⏰",
  "bomb": "💣",
  "knife": "🔪",
  "shield": "🛡️",
  "label": "🏷️",
  "bookmark": "🔖",
  "package": "📦",
  "mailbox": "📫",
  "envelope": "✉️",
  "scroll": "📜",
  "book": "📖",
  "telescope": "🔭",
  "microscope": "🔬",
  "pill": "💊",
  "dna": "🧬",
  "test_tube": "🧪",
  "check": "✅",
  "x": "❌",
  "warning": "⚠️",
  "question": "❓",
  "exclamation": "❗",
  "no_entry": "⛔",
  "prohibited": "🚫",
  "recycle": "♻️",
  "infinity": "♾️",
  "plus": "➕",
  "minus": "➖",
  "multiply": "✖️",
  "equals": "🟰",
  "arrow_right": "➡️",
  "arrow_left": "⬅️",
  "arrow_up": "⬆️",
  "arrow_down": "⬇️",
  "refresh": "🔄",
  "new": "🆕",
  "free": "🆓",
  "cool": "🆒",
  "sos": "🆘",
  "atm": "🏧",
  "no_sound": "🔇",
  "tada": "🎉",
  "confetti": "🎊",
  "balloon": "🎈",
  "ribbon": "🎀",
  "gift": "🎁",
  "trophy_sym": "🏆",
  "rocket": "🚀",
  "airplane": "✈️",
  "satellite": "🛰️",
  "ufo": "🛸",
  "anchor": "⚓",
  "fuel": "⛽",
  "stopwatch": "⏱️",
  "timer_clock": "⏲️",
  "world_map": "🗺️",
  "flag_white": "🏳️",
  "flag_black": "🏴",
  "pirate_flag": "🏴‍☠️",
  "checkered_flag": "🏁",
  "rainbow_flag": "🏳️‍🌈",
  "zap": "⚡",
};

export const EMOJI_CATS: EmojiCat[] = [
  { slug: "smileys", icon: "😀", title: "😀 Smileys & Emotion", names: ["smile", "grin", "joy", "rofl", "wink", "blush", "innocent", "heart_eyes", "star_struck", "kissing_heart", "kissing", "yum", "stuck_out_tongue", "stuck_out_tongue_wink", "zany", "raised_eyebrow", "monocle", "nerd", "sunglasses", "disguised", "partying", "smirk", "unamused", "disappointed", "worried", "angry", "rage", "cry", "sob", "scream", "flushed", "pleading", "melting", "cold_face", "hot_face", "nauseated", "mind_blown", "sleeping", "drool", "thinking", "shush", "zipper_mouth", "peeking", "salute", "dotted_face", "skull", "clown", "ghost", "alien", "robot", "poop", "money", "cowboy", "rolling_eyes", "grimace", "relieved", "shrug", "facepalm", "hugs", "pensive", "confused", "upside_down", "moai"] },
  { slug: "gestures", icon: "👋", title: "gestures", names: ["thumbsup", "thumbsdown", "clap", "wave", "wave_hand", "pray", "handshake", "point_up", "point_right", "point_left", "point_down", "ok_hand", "pinch", "v", "love_you", "metal", "call_me", "crossed", "muscle", "brain", "eyes", "eye", "tongue", "lips", "palms_up", "heart_hands", "middle_finger", "raised_fist", "fist", "palm", "pinching", "writing", "nail_polish"] },
  { slug: "hearts", icon: "❤️", title: "hearts", names: ["heart", "orange_heart", "yellow_heart", "green_heart", "blue_heart", "purple_heart", "black_heart", "white_heart", "brown_heart", "pink_heart", "broken_heart", "heart_fire", "heart_exclamation", "two_hearts", "revolving_hearts", "heartbeat", "heartpulse", "sparkling_heart", "cupid", "gift_heart", "heart_decoration", "kiss_mark", "hundred", "anger", "boom", "dizzy", "sweat_drops", "fire", "sparkles", "star", "glowing_star", "shooting_star"] },
  { slug: "music", icon: "🎵", title: "music", names: ["notes", "musical_note", "headphones", "guitar", "cd", "vinyl", "mic", "speaker", "mute", "studio_mic", "radio", "saxophone", "accordion", "drum", "piano", "trumpet", "violin", "banjo", "maracas", "long_drum", "movie", "tv", "camera", "video_camera", "clapper", "film", "projector", "popcorn", "ticket", "loudly_crying", "bell", "mega"] },
  { slug: "nature", icon: "🌿", title: "nature", names: ["dog", "cat", "fox", "wolf", "bear", "panda", "koala", "tiger", "lion", "unicorn", "horse", "cow", "pig", "frog", "monkey", "chicken", "penguin", "bird", "eagle", "bat", "owl", "butterfly", "bee", "ladybug", "snake", "octopus", "whale", "dolphin", "fish", "shark", "turtle", "dragon", "cactus", "tree", "palm_tree", "seedling", "herb", "four_leaf", "mushroom", "rose", "cherry_blossom", "sunflower", "rainbow", "snowflake", "tornado", "ocean", "crescent_moon", "sun"] },
  { slug: "food", icon: "🍕", title: "🍔 Food & Drink", names: ["pizza", "hamburger", "fries", "hotdog", "taco", "burrito", "sushi", "ramen", "spaghetti", "rice", "curry", "bento", "egg", "pancakes", "waffle", "bacon", "steak", "croissant", "bread", "bagel", "pretzel", "apple", "grapes", "watermelon", "strawberry", "peach", "mango", "banana", "avocado", "ice_cream", "donut", "cookie", "cake", "chocolate", "candy", "lollipop", "beers", "wine", "cocktail", "champagne", "coffee", "tea", "bubble_tea", "juice", "milk", "beer", "tropical_drink", "mate"] },
  { slug: "activities", icon: "🎮", title: "⚽ Activities", names: ["trophy", "medal", "gold_medal", "silver_medal", "bronze_medal", "soccer", "basketball", "football", "baseball", "tennis", "volleyball", "rugby", "cricket", "golf", "ping_pong", "badminton", "boxing", "skateboard", "surfing", "swimming", "biking", "running", "yoga", "climbing", "video_game", "joystick", "dice", "puzzle", "chess", "dart", "bowling", "billiards", "slot_machine", "fishing", "kite"] },
  { slug: "objects", icon: "💡", title: "💡 Objects", names: ["bulb", "flashlight", "candle", "gem", "crown", "ring", "money_bag", "dollar", "credit_card", "chart", "chart_down", "calendar", "clipboard", "pushpin", "paperclip", "scissors", "lock", "unlock", "key", "hammer", "wrench", "gear", "magnet", "link", "battery", "plug", "computer", "phone", "hourglass", "alarm", "bomb", "knife", "shield", "label", "bookmark", "package", "mailbox", "envelope", "scroll", "book", "telescope", "microscope", "pill", "dna", "test_tube"] },
  { slug: "symbols", icon: "✅", title: "🔣 Symbols", names: ["check", "x", "warning", "question", "exclamation", "no_entry", "prohibited", "recycle", "infinity", "plus", "minus", "multiply", "equals", "arrow_right", "arrow_left", "arrow_up", "arrow_down", "refresh", "new", "free", "cool", "sos", "atm", "no_sound", "tada", "confetti", "balloon", "ribbon", "gift", "trophy_sym", "rocket", "airplane", "satellite", "ufo", "anchor", "fuel", "stopwatch", "timer_clock", "world_map", "flag_white", "flag_black", "pirate_flag", "checkered_flag", "rainbow_flag", "zap"] },
];

export interface AnimEmoji { cp: string; u: string; name: string; }
export const ANIMATED_EMOJI: Record<string, AnimEmoji> = {
  "a_fire": {
    "cp": "1f525",
    "u": "🔥",
    "name": "fire"
  },
  "a_party": {
    "cp": "1f973",
    "u": "🥳",
    "name": "party"
  },
  "a_tada": {
    "cp": "1f389",
    "u": "🎉",
    "name": "tada"
  },
  "a_joy": {
    "cp": "1f602",
    "u": "😂",
    "name": "joy"
  },
  "a_rofl": {
    "cp": "1f923",
    "u": "🤣",
    "name": "rofl"
  },
  "a_heart": {
    "cp": "2764_fe0f",
    "u": "❤️",
    "name": "heart"
  },
  "a_heart_fire": {
    "cp": "2764_fe0f_200d_1f525",
    "u": "❤️‍🔥",
    "name": "heart_fire"
  },
  "a_heart_eyes": {
    "cp": "1f60d",
    "u": "😍",
    "name": "heart_eyes"
  },
  "a_sparkles": {
    "cp": "2728",
    "u": "✨",
    "name": "sparkles"
  },
  "a_star": {
    "cp": "2b50",
    "u": "⭐",
    "name": "star"
  },
  "a_skull": {
    "cp": "1f480",
    "u": "💀",
    "name": "skull"
  },
  "a_rocket": {
    "cp": "1f680",
    "u": "🚀",
    "name": "rocket"
  },
  "a_hundred": {
    "cp": "1f4af",
    "u": "💯",
    "name": "hundred"
  },
  "a_thumbsup": {
    "cp": "1f44d",
    "u": "👍",
    "name": "thumbsup"
  },
  "a_clap": {
    "cp": "1f44f",
    "u": "👏",
    "name": "clap"
  },
  "a_wave": {
    "cp": "1f44b",
    "u": "👋",
    "name": "wave"
  },
  "a_sunglasses": {
    "cp": "1f60e",
    "u": "😎",
    "name": "sunglasses"
  },
  "a_mindblown": {
    "cp": "1f92f",
    "u": "🤯",
    "name": "mindblown"
  },
  "a_sob": {
    "cp": "1f62d",
    "u": "😭",
    "name": "sob"
  },
  "a_melting": {
    "cp": "1fae0",
    "u": "🫠",
    "name": "melting"
  },
  "a_thinking": {
    "cp": "1f914",
    "u": "🤔",
    "name": "thinking"
  },
  "a_pleading": {
    "cp": "1f97a",
    "u": "🥺",
    "name": "pleading"
  },
  "a_scream": {
    "cp": "1f631",
    "u": "😱",
    "name": "scream"
  },
  "a_nerd": {
    "cp": "1f913",
    "u": "🤓",
    "name": "nerd"
  },
  "a_monocle": {
    "cp": "1f9d0",
    "u": "🧐",
    "name": "monocle"
  },
  "a_hot": {
    "cp": "1f975",
    "u": "🥵",
    "name": "hot"
  },
  "a_cold": {
    "cp": "1f976",
    "u": "🥶",
    "name": "cold"
  },
  "a_salute": {
    "cp": "1fae1",
    "u": "🫡",
    "name": "salute"
  },
  "a_money": {
    "cp": "1f911",
    "u": "🤑",
    "name": "money"
  },
  "a_ghost": {
    "cp": "1f47b",
    "u": "👻",
    "name": "ghost"
  },
  "a_alien": {
    "cp": "1f47d",
    "u": "👽",
    "name": "alien"
  },
  "a_robot": {
    "cp": "1f916",
    "u": "🤖",
    "name": "robot"
  },
  "a_poop": {
    "cp": "1f4a9",
    "u": "💩",
    "name": "poop"
  },
  "a_check": {
    "cp": "2705",
    "u": "✅",
    "name": "check"
  },
  "a_boom": {
    "cp": "1f4a5",
    "u": "💥",
    "name": "boom"
  },
  "a_zap": {
    "cp": "26a1",
    "u": "⚡",
    "name": "zap"
  },
  "a_coffee": {
    "cp": "2615",
    "u": "☕",
    "name": "coffee"
  },
  "a_notes": {
    "cp": "1f3b6",
    "u": "🎶",
    "name": "notes"
  },
  "a_guitar": {
    "cp": "1f3b8",
    "u": "🎸",
    "name": "guitar"
  },
  "a_eyes": {
    "cp": "1f440",
    "u": "👀",
    "name": "eyes"
  },
  "a_dance": {
    "cp": "1f483",
    "u": "💃",
    "name": "dance"
  },
  "a_cat": {
    "cp": "1f431",
    "u": "🐱",
    "name": "cat"
  },
  "a_dog": {
    "cp": "1f415",
    "u": "🐕",
    "name": "dog"
  },
  "a_unicorn": {
    "cp": "1f984",
    "u": "🦄",
    "name": "unicorn"
  },
  "a_rainbow": {
    "cp": "1f308",
    "u": "🌈",
    "name": "rainbow"
  },
  "a_crown": {
    "cp": "1f451",
    "u": "👑",
    "name": "crown"
  },
  "a_gem": {
    "cp": "1f48e",
    "u": "💎",
    "name": "gem"
  },
  "a_pizza": {
    "cp": "1f355",
    "u": "🍕",
    "name": "pizza"
  },
  "a_cake": {
    "cp": "1f382",
    "u": "🎂",
    "name": "cake"
  },
  "a_muscle": {
    "cp": "1f4aa",
    "u": "💪",
    "name": "muscle"
  }
};

export function animEmojiUrl(key: string): string {
  const info = ANIMATED_EMOJI[key];
  return info ? `https://fonts.gstatic.com/s/e/notoemoji/latest/${info.cp}/512.webp` : "";
}
